version: '3.9'

services:

  nodejs:
    container_name: nodejs
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - '3000:3000'

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - '5432:5432'
    networks:
      - app-connect

volumes:
  postgres-data:

networks:
  app-connect:
      driver: bridge
