name: Backend CI

on:
  push:
    paths:
        - frontend/**
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Test application
        run: yarn test

      - name: Build application
        run: yarn build

      - name: Restart server application
        run: |
          docker-compose down
          docker-compose up --build
